# Generated by Django 2.1.4 on 2018-12-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('day', models.DateField(verbose_name='advert day')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='automodel',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Maker'),
        ),
        migrations.AddField(
            model_name='advert',
            name='ad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Person'),
        ),
        migrations.AddField(
            model_name='advert',
            name='automodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.AutoModel'),
        ),
        migrations.AddField(
            model_name='advert',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Body'),
        ),
        migrations.AddField(
            model_name='advert',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Color'),
        ),
    ]
