# Generated by Django 2.1.4 on 2018-12-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakerAndModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Maker')),
            ],
        ),
        migrations.RemoveField(
            model_name='automodel',
            name='maker',
        ),
        migrations.AddField(
            model_name='advert',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auto.Maker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makerandmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.AutoModel'),
        ),
    ]
