# Generated by Django 2.1.4 on 2018-12-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20181224_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='ad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Person', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='automodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.AutoModel', verbose_name='Модель машины'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Body', verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Color', verbose_name='Цвет кузова'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Maker', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
