# Generated by Django 2.1.4 on 2018-12-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_20181224_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ['maker']},
        ),
    ]
