# Generated by Django 2.1.4 on 2019-01-11 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20181226_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активно ли объявление'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='ad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='user_pic'),
        ),
    ]
